export const lessons = [
  { id: 'pix', title: 'Golpes com Pix', icon: 'repeat', color: '#16836F', bg: '#E7F7F1', summary: 'Confira antes de transferir.', intro: 'Alguém pode se passar por um familiar ou funcionário do banco para pedir dinheiro. A pressa é um sinal de alerta.', tips: ['Confirme pedidos de dinheiro por uma ligação para um número que você já conhece.', 'Confira o nome do recebedor e o valor na tela do banco antes de confirmar.', 'Não transfira para uma suposta conta segura por orientação de uma ligação. Procure o banco pelo aplicativo oficial.'] },
  { id: 'boleto', title: 'Boletos falsos', icon: 'file-text', color: '#AD7423', bg: '#FFF4E3', summary: 'Nem toda cobrança é verdadeira.', intro: 'Um boleto falso pode parecer igual ao original. Confira os dados que aparecem no aplicativo do banco antes de pagar.', tips: ['Busque a cobrança no aplicativo ou site oficial da empresa.', 'Confira beneficiário, documento e valor na tela de pagamento. O logotipo do boleto não garante sua autenticidade.', 'Se houver diferença nos dados, fale com a empresa por um contato oficial antes de pagar.'] },
  { id: 'whatsapp', title: 'Golpes no WhatsApp', icon: 'message-circle', color: '#269268', bg: '#E9F7EF', summary: 'Proteja sua conta e suas conversas.', intro: 'Criminosos podem usar a foto de alguém conhecido em outro número ou tentar tomar sua conta pedindo um código.', tips: ['Nunca compartilhe códigos recebidos por SMS.', 'Ative a confirmação em duas etapas nas configurações da conta.', 'Desconfie de um novo número pedindo dinheiro. Confirme a identidade por outro canal conhecido.'] },
  { id: 'lojas', title: 'Lojas falsas', icon: 'shopping-bag', color: '#7860BA', bg: '#F1EDFB', summary: 'Compre com mais tranquilidade.', intro: 'Uma oferta muito barata pode levar a uma loja falsa. Aparência bonita e cadeado no navegador não bastam para confiar.', tips: ['Desconfie de preços muito abaixo do mercado e de mensagens que pressionam a comprar com urgência.', 'Confira o endereço do site e procure informações sobre a empresa fora da própria loja.', 'Confira os dados do recebedor e as condições de entrega. Na dúvida, não conclua a compra.'] },
];
export const questions = [
  { sender: 'Número desconhecido', message: 'Oi, mãe! Troquei de número. Preciso pagar uma conta agora, mas meu banco está bloqueado. Faz um Pix de R$ 850 para mim? Depois te explico!', scam: true, explanation: 'O número novo, a urgência e o pedido de dinheiro são sinais de golpe. Ligue para o número antigo da pessoa antes de transferir.' },
  { sender: 'Aplicativo oficial do banco', message: 'Você abriu o aplicativo oficial do banco. Antes de confirmar o Pix, a tela mostra o nome do recebedor e pede que você confira os dados.', scam: false, explanation: 'Nesse contexto, conferir os dados dentro do aplicativo oficial faz parte do pagamento. Continue apenas se o recebedor e o valor forem os esperados.' },
  { sender: 'Suposto suporte', message: 'Seu WhatsApp será bloqueado em 10 minutos. Envie o código de 6 dígitos que chegou por SMS para manter sua conta ativa.', scam: true, explanation: 'Nunca envie códigos de confirmação a outras pessoas. Eles podem permitir o acesso à sua conta. A ameaça de bloqueio tenta fazer você agir sem pensar.' },
];
