import { Platform, StyleSheet } from 'react-native';
export const createStyles = (C) => StyleSheet.create({
  app: { flex: 1, flexDirection: 'row', backgroundColor: C.bg },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12 }, between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  logo: { width: 36, height: 40, borderRadius: 12, backgroundColor: C.primary, alignItems: 'center', justifyContent: 'center' }, brand: { fontSize: 21, fontWeight: '800', color: C.ink, letterSpacing: -.9 },
  authPage: { flexGrow: 1, backgroundColor: C.surface }, story: { backgroundColor: C.primary, padding: 52, overflow: 'hidden' }, storyBody: { paddingVertical: 46, flex: 1, justifyContent: 'center' }, eyebrowLight: { color: '#C4DEFF', fontSize: 12, letterSpacing: 2, fontWeight: '700' }, storyTitle: { color: 'white', fontSize: 46, fontWeight: '700', lineHeight: 55, marginTop: 20, letterSpacing: -1.6 }, storyDescription: { color: '#E0EBFF', fontSize: 18, lineHeight: 29, marginTop: 22, maxWidth: 450 }, storyFeature: { color: 'white', fontSize: 16 }, storyFoot: { color: '#C4DEFF', fontSize: 11, letterSpacing: 2 },
  art: { height: 260, alignItems: 'center', justifyContent: 'center', marginTop: 20 }, heroArt: { width: 240, alignItems: 'center', justifyContent: 'center' }, orbit: { width: 230, height: 230, borderRadius: 130, borderWidth: 1, borderColor: '#FFFFFF30', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF09' }, orbitInner: { width: 185, height: 185, borderRadius: 100, borderColor: '#FFFFFF25', borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, shield: { width: 118, height: 134, backgroundColor: C.pale, borderRadius: 30, borderBottomLeftRadius: 60, borderBottomRightRadius: 60, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-8deg' }] }, artTag: { position: 'absolute', bottom: 12, backgroundColor: C.surface, borderRadius: 12, padding: 14, flexDirection: 'row', gap: 8, alignItems: 'center', transform: [{ rotate: '-4deg' }] },
  authMain: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28 }, authForm: { width: '100%', maxWidth: 420, paddingVertical: 30 }, kicker: { fontSize: 11, letterSpacing: 1.7, fontWeight: '800', color: C.blue }, authTitle: { fontSize: 32, fontWeight: '700', color: C.ink, letterSpacing: -1, marginTop: 14 }, description: { fontSize: 16, color: C.muted, lineHeight: 25, marginTop: 10, marginBottom: 22 }, demoNote: { backgroundColor: C.pale, borderRadius: 10, padding: 13, marginBottom: 22 }, demoText: { color: '#4C6284', fontSize: 13, lineHeight: 20 },
  field: { marginBottom: 18 }, label: { fontSize: 15, fontWeight: '600', color: C.ink, lineHeight: 22 }, inputWrap: { flexDirection: 'row', borderWidth: 1, borderColor: '#DCE3ED', borderRadius: 10, marginTop: 8, backgroundColor: C.surface }, input: { flex: 1, minWidth: 0, minHeight: 54, paddingHorizontal: 15, fontSize: 16, color: C.ink, ...(Platform.OS === 'web' ? { outlineStyle: 'none' } : {}) }, show: { justifyContent: 'center', alignItems: 'center', width: 48, minHeight: 48 }, error: { color: '#B63D3D', fontSize: 13, marginTop: 6 },
  button: { minHeight: 50, backgroundColor: C.primary, borderRadius: 10, paddingHorizontal: 18, paddingVertical: 14, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: 'white', fontSize: 15, fontWeight: '600', textAlign: 'center' }, secondary: { backgroundColor: C.pale, borderWidth: 1, borderColor: C.secondaryBorder }, link: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 4 }, linkText: { color: C.blue, fontSize: 14, fontWeight: '600' }, divider: { flexDirection: 'row', alignItems: 'center', gap: 16, marginVertical: 20 }, rule: { height: 1, backgroundColor: C.line, flex: 1 }, switchRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'center', gap: 7, marginTop: 18 }, authFoot: { fontSize: 13, color: C.muted, textAlign: 'center', marginTop: 30 }, small: { fontSize: 14, color: C.muted, lineHeight: 22 }, tiny: { fontSize: 12, color: C.muted, lineHeight: 19 }, body: { fontSize: 16, lineHeight: 26, color: C.body },
  sidebar: { width: 246, backgroundColor: C.surface, borderRightWidth: 1, borderColor: C.line, padding: 26, paddingTop: 32 }, navItem: { flexDirection: 'row', alignItems: 'center', gap: 14, padding: 14, marginBottom: 8, borderRadius: 10, minHeight: 52 }, navActive: { backgroundColor: C.pale }, navText: { fontSize: 15, fontWeight: '600', color: C.muted }, navDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: C.primary, marginLeft: 'auto' }, sidebarTip: { backgroundColor: C.bg, padding: 18, borderRadius: 14, gap: 12, marginBottom: 24 },
  themeToggle: { width: 44, height: 44, borderRadius: 14, borderWidth: 1, borderColor: C.line, backgroundColor: C.pale, alignItems: 'center', justifyContent: 'center' },
  topbar: { minHeight: 86, paddingHorizontal: 38, paddingVertical: 16, backgroundColor: C.surface, borderBottomWidth: 1, borderColor: C.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, badge: { borderRadius: 20, backgroundColor: C.pale, paddingHorizontal: 10, paddingVertical: 5 }, avatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: C.pale, alignItems: 'center', justifyContent: 'center' }, mobileNav: { flexDirection: 'row', justifyContent: 'space-around', backgroundColor: C.surface, borderBottomWidth: 1, borderColor: C.line }, dashboard: { padding: 38, flexGrow: 1 }, content: { width: '100%', maxWidth: 1250, alignSelf: 'center' }, pageTitle: { fontSize: 32, color: C.ink, fontWeight: '700', letterSpacing: -.8, marginTop: 10 },
  hero: { backgroundColor: C.primary, borderRadius: 20, padding: 32, flexDirection: 'row', overflow: 'hidden', gap: 10 }, heroBadge: { alignSelf: 'flex-start', backgroundColor: '#FFFFFF1C', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 7 }, heroBadgeText: { color: '#E1EEFF', fontSize: 10, letterSpacing: 1, fontWeight: '600' }, heroTitle: { fontSize: 36, fontWeight: '700', color: 'white', lineHeight: 43, marginTop: 18, letterSpacing: -.8, maxWidth: 370 }, heroDescription: { fontSize: 16, color: '#DFEBFF', lineHeight: 25, marginTop: 12, maxWidth: 450 }, heroButton: { alignSelf: 'flex-start', marginTop: 24, backgroundColor: C.surface },
  stats: { flexDirection: 'row', marginTop: 20, backgroundColor: C.surface, borderRadius: 14, borderWidth: 1, borderColor: C.line, paddingVertical: 22 }, stat: { flex: 1, paddingHorizontal: 20, justifyContent: 'center', gap: 4 }, statNumber: { fontSize: 29, fontWeight: '700', color: C.ink }, statTotal: { fontSize: 19, color: C.muted, fontWeight: '400' }, track: { height: 5, backgroundColor: C.pale, borderRadius: 5, marginTop: 8 }, fill: { height: 5, backgroundColor: C.primary, borderRadius: 5 },
  lower: { flexDirection: 'row', gap: 26, marginTop: 30, alignItems: 'stretch' }, sectionHeading: { minHeight: 42, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }, sectionTitle: { fontSize: 19, fontWeight: '700', color: C.ink }, lessonGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 16 }, lessonCard: { backgroundColor: C.surface, padding: 20, borderRadius: 14, borderWidth: 1, borderColor: C.line }, topicIcon: { width: 43, height: 43, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, lessonTitle: { fontSize: 17, fontWeight: '700', color: C.ink, marginTop: 17, marginBottom: 7 }, quizCard: { backgroundColor: C.surface, borderWidth: 1, borderColor: C.line, borderRadius: 16, padding: 24, marginTop: 5 }, cardTitle: { fontSize: 23, fontWeight: '700', color: C.ink, marginTop: 15, marginBottom: 10 }, message: { backgroundColor: C.message, borderRadius: 12, padding: 18, marginVertical: 22 }, avatarSmall: { width: 34, height: 34, backgroundColor: C.avatar, borderRadius: 17, alignItems: 'center', justifyContent: 'center' }, messageText: { fontSize: 16, lineHeight: 26, color: C.ink, marginTop: 18, marginBottom: 12 }, feedback: { padding: 16, gap: 8, borderRadius: 10, marginBottom: 16 }, lessonDetail: { backgroundColor: C.surface, borderWidth: 1, borderColor: C.line, borderRadius: 16, padding: 26 }, step: { backgroundColor: C.pale, color: C.blue, fontWeight: '700', borderRadius: 8, paddingVertical: 3, paddingHorizontal: 10, overflow: 'hidden' }, bottomNote: { marginTop: 36, gap: 12, borderTopWidth: 1, borderColor: C.line, paddingTop: 22, paddingBottom: 10 },
});
